module "platform" {
  source = "../../modules/platform"

  project_name                = var.project_name
  environment                 = var.environment
  location                    = var.location
  tags                        = var.tags
  vnet_address_space          = var.vnet_address_space
  subnet_frontend_cidr        = var.subnet_frontend_cidr
  subnet_backend_cidr         = var.subnet_backend_cidr
  subnet_database_cidr        = var.subnet_database_cidr
  storage_account_name        = var.storage_account_name
  storage_retention_days      = var.storage_retention_days
  acr_name                    = var.acr_name
  acr_sku                     = var.acr_sku
  key_vault_name              = var.key_vault_name
  postgres_server_name        = var.postgres_server_name
  postgres_version            = var.postgres_version
  postgres_sku_name           = var.postgres_sku_name
  postgres_storage_mb         = var.postgres_storage_mb
  postgres_backup_retention_days = var.postgres_backup_retention_days
  postgres_admin_username     = var.postgres_admin_username
  postgres_database_name      = var.postgres_database_name
  backend_service_plan_sku    = var.backend_service_plan_sku
  frontend_service_plan_sku   = var.frontend_service_plan_sku
  backend_node_version        = var.backend_node_version
  backend_python_version      = var.backend_python_version
  frontend_node_version       = var.frontend_node_version
  frontend_python_version     = var.frontend_python_version
}